# ---
# - name: Creates directory
#   file:
#     path: ~/backend-app
#     state: directory

# - name: Extract artifact
#   unarchive:
#     src: artifact.tar.gz
#     dest: ~/backend-app

# - name: Install dependencies
#   shell: |
#     cd ~/backend-app
#     npm i

# - name: Executing node
#   shell: |
#     cd ~/backend-app
#     npm install
#     npm run build
#     sudo npm install forever -g
#     sudo npm install ts-node -g
#     forever start -c "ts-node -r tsconfig-paths/register -r dotenv/config scr/main.ts" ./
#   register: execute_node

# - name: Print message
#   debug:
#     msg: "{{ execute_node.stdout_lines }}"

# - name: Configure and Start PM2
#   become: true
#   shell: |
#     env PATH=$PATH:/usr/local/bin pm2 startup systemd -u ubuntu --hp /home/ubuntu

---
- name: Creates directory
  file:
    path: ~/backend-app
    state: directory

- name: Copy folder to host
  copy:
    src: ~/project/backend
    dest: ~/backend-app

- name: Executing node
  shell: |
    cd ~/backend-app/backend
    npm install
    npm run build
    pm2 start npm -- start
- name: Sleep 10s to wait server before smoke-test
  ansible.builtin.pause:
    seconds: 10