---
- name: Creates directory
  file:
    path: ~/backend-app
    state: directory

- name: Extract artifact
  unarchive:
    src: artifact.tar.gz
    dest: ~/backend-app

- name: Install dependencies
  shell: |
    cd ~/backend-app
    npm i

- name: Executing node
  shell: |
    cd ~/backend-app
    npm install
    npm run build
    pm2 stop all
    pm2 start npm --name "udapeople-backend" -- run start

- name: "Set pm2 start as service"
  become: yes
  shell: |
    env PATH=$PATH:/usr/local/bin pm2 startup -u ubuntu

- name: check pm2 status
  become: yes
  shell: |
    pm2 describe "udapeople-backend"
  register: command_output_npm
- debug: var=command_output_npm.stdout_lines

- name: Sleep 10s to wait server before smoke-test
  ansible.builtin.pause:
    seconds: 10